# -*- coding: utf-8 -*-
import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
s = open(r'C:\Users\youzi\Doubao\chats\2026-09-03\new-chat\MSA系统\index.html', encoding='utf-8').read()
print('工厂Select总数', s.count('placeholder="工厂"'))
print('车间Select总数', s.count('placeholder="车间"'))
print('器具组工厂Select', s.count('placeholder="工厂" style={{width:140}} options={PLANTS_OPT} value={fPlant}'))
print('mcat过滤', s.count('(!q.mcat || i.mcat===q.mcat)'))
print('器具组plant过滤', s.count('(!q.plant||g.plant===q.plant) && (!q.sub||g.subplant===q.sub)'))
print('MSA计划source过滤', s.count('sourceMatch = !qSource'))
print('特性类别过滤', s.count('!fCat2 || r.category===fCat2'))
print('工序过滤', s.count('!fProc2 || r.processName===fProc2'))
print('方法过滤', s.count('!fMethod || m.code===fMethod'))
print('合并过滤', s.count('(m.canMerge||\'否\')===fMerge'))
print('样本库std过滤', s.count('!q.std||r.standardId===q.std'))
print('台账anl过滤', s.count('!q.anl || r.analyst===q.anl'))
